// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsxVWq71HIhhG-ApVmHLlOgDF3ePDU0cA',
    appId: '1:720419734316:web:fc092d369d7028eb8da289',
    messagingSenderId: '720419734316',
    projectId: 'todo-app-965c9',
    authDomain: 'todo-app-965c9.firebaseapp.com',
    storageBucket: 'todo-app-965c9.appspot.com',
    measurementId: 'G-PG0WJ02B98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsXKsQ7bYMdlIaeNg7CE7L3nuhRxwGVCU',
    appId: '1:720419734316:android:8b3e0581a41b05588da289',
    messagingSenderId: '720419734316',
    projectId: 'todo-app-965c9',
    storageBucket: 'todo-app-965c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxv7h7f27mfN5tuJirKKx-R2MuKT-LwtI',
    appId: '1:720419734316:ios:d85743b17aa354fe8da289',
    messagingSenderId: '720419734316',
    projectId: 'todo-app-965c9',
    storageBucket: 'todo-app-965c9.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxv7h7f27mfN5tuJirKKx-R2MuKT-LwtI',
    appId: '1:720419734316:ios:909c0c5b5ac6d7528da289',
    messagingSenderId: '720419734316',
    projectId: 'todo-app-965c9',
    storageBucket: 'todo-app-965c9.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
